### PR TITLE
Edits

### LINKED ISSUE #42: Component to render syntactical and validity edits
The links that cause these components to render is from #35.

syn-val

This table can be used for both syntactical and validity edits.
Initially show the rows with a column containing loan number and then number of errors. The number of errors will be a link to the more detailed information.

Data required:
- loan number
- number of errors
- edit id
- edit description
- field where the error occurred
- the incorrect data that was submitted
- _action to be taken (this may not be required, all errors in syntactical and validity require correction and for the file to be re-uploaded_

While there may be no link generated from #35, there are no errors present, this component should still be capable of showing a message. A filer could still navigate to `/edits/syntactical` or `/edits/validity` (see #37) so they should see a message saying something like `There are no [editType] errors. Please continue to the next step.`.

### PR DESCRIPTION
**Pull request by awolfe76**
- starts edit screens for syntax and validity edits
- adds CSS for them
- has hardcoded data for now (see #77)
- will also break out a few more components (see #78 and #79)
- for now the route is `/edits/` (may change in a future PR)
- results are currently all expanded (see #80)

Screenshot:

edits

Closes #42

### CODE REVIEW

**Comment by awolfe76** [comment]
@wpears - should be ok to review now. I've created a few other issues to clean up some items in this PR.

File: src/js/EditsContainer.jsx [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+    	"edits": {
+    		"syntactical": [],
+    		"validity": [],
+    		"quality": [],
+    		"macro": []
+    	}
+    }
+  },
+
+  componentDidMount: function() {
```
Comment (wpears) [inline src/js/EditsContainer.jsx]: `componentDidMount` should be `componentWillMount`, otherwise you'll be waiting on the first render before setting the initial data

**Comment by wpears** [comment]
Looks good, just the one comment on componentDidMount

**Comment by awolfe76** [comment]
Good call @wpears. I'll merge once Travis gives the ok.
