### PR TITLE
Upload bugs

### LINKED ISSUE #470: Upload page temporarily freezes after pressing "Upload"
When I uploaded a large file (`clean_14117-lars.txt`), I saw about a 4 second lag between pressing the "upload" button and seeing the gray/green dots that show the status of "uploading", "parsing", "validating".

Not sure if it's avoidable, but I wanted to let you know.

### LINKED ISSUE #477: Cancel polling on selecting a file

### PR DESCRIPTION
**Pull request by wpears**
Closes #477 
Closes #470

### CODE REVIEW

File: src/js/reducers/index.js [hunk 1]
```diff
@@ -18,6 +18,7 @@ import {
   SHOW_CONFIRM,
   HIDE_CONFIRM,
   PICK_SORT,
+  UPLOAD_START,
```
Comment (awolfe76) [inline src/js/reducers/index.js:21]: Shouldn't this require a change to `constants` too?

File: src/js/actions/index.js [hunk 2]
```diff
@@ -26,6 +26,7 @@ import fileSaver from 'file-saver'
 
 let latestSubmissionId
 let currentFilingPeriod
+const pollObj = {polling: false}
```
Comment (awolfe76) [inline src/js/actions/index.js:29]: Why an object here?

File: src/js/reducers/index.js (hunk 1 above)
Comment (wpears) [reply src/js/reducers/index.js:21]: It was already in constants, just wasn't being mapped to the state.

File: src/js/actions/index.js (hunk 2 above)
Comment (wpears) [reply src/js/actions/index.js:29]: So that `pollForProgress can be passed a value that can be altered externally. Using an object means you can:
 - in the tests for `pollForProgress` pass in the value to check the behavior for each condition
 - change the polling value externally (ie from `setFile` or `setNewFile`

If it was just a boolean, you couldn't meet both these conditions simultaneously

Comment (awolfe76) [reply src/js/actions/index.js:29]: Thanks!

**Review by awolfe76 — APPROVED** [review]
👍
