### PR TITLE
Pass fetched prop to EditsHeaderDescription

### LINKED ISSUE #975: Show LoadingIcon near EditsHeaderDescription
With #974, the (X edits found) will render and be initially incorrect. This should key off the `fetched` status of a given type to either display a LoadingIcon as more results come in (preferred) or just render null until all results are in.

### PR DESCRIPTION
**Pull request by wpears**
Closes #975

### CODE REVIEW

File: src/js/components/EditsHeaderDescription.jsx [hunk 1]
```diff
@@ -32,13 +33,13 @@ export const getText = editType => {
   throw new Error('Unexpected edit type. Unable to create edit description.')
 }
 
-const EditsHeaderDescription = ({ type, count }) => {
+const EditsHeaderDescription = ({ type, count, fetched }) => {
```
Comment (awolfe76) [inline src/js/components/EditsHeaderDescription.jsx:36]: We should add `fetched` as a `propType`.

**Review by awolfe76 — CHANGES_REQUESTED** [review]
Just the `propType`, otherwise 👍 .

**Review by awolfe76 — APPROVED** [review]
