### PR TITLE
Remove cluttered output and fixup testing errors

### LINKED ISSUE #827: Clean up tests
When running `jest` (or `yarn run test`) there are warnings that appear. Note that they don't cause the tests to fail, but it would be nice to clean these up.

A few examples:

```
console.error node_modules/fbjs/lib/warning.js:35
Warning: validateDOMNesting(...): <td> cannot appear as a child of <div>. See div > EditsTableCell > td.
```

```
console.error src/js/actions/fetchInstitution.js:24
      TypeError: Cannot read property 'filingPeriod' of undefined
          at /Users/wolfea/Documents/projects/hmda-platform-ui/src/js/actions/fetchEachFiling.js:8:32
          at /Users/wolfea/Documents/projects/hmda-platform-ui/node_modules/redux-thunk/lib/index.js:11:18
          at dispatch (/Users/wolfea/Documents/projects/hmda-platform-ui/node_modules/redux/lib/applyMiddleware.js:45:18)
          at /Users/wolfea/Documents/projects/hmda-platform-ui/src/js/actions/fetchInstitution.js:20:18
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
```

```
console.error node_modules/fbjs/lib/warning.js:35
      Warning: Failed prop type: The prop `isFetching` is marked as required in `Verifier`, but its value is `undefined`.
          in Verifier
```

There are also a few `console.log` that show up which should be cleaned up in #815.

### PR DESCRIPTION
**Pull request by wpears**
Closes #827

### CODE REVIEW

File: __tests__/api/fetch.js [hunk 1]
```diff
@@ -1,5 +1,6 @@
 jest.unmock('../../src/js/api/fetch')
 import { fetch } from '../../src/js/api/fetch'
+console.log = jest.fn()
```
Comment (awolfe76) [inline __tests__/api/fetch.js]: Do we need this here?

**Review by awolfe76 — APPROVED** [review]
