### PR TITLE
Upload bug

### LINKED ISSUE #771: First upload shows as 100%

### PR DESCRIPTION
**Pull request by wpears**
Fixes #771

### CODE REVIEW

File: src/js/components/ValidationProgress.jsx [hunk 1]
```diff
@@ -78,8 +78,11 @@ export default class ValidationProgress extends Component {
 
     if (code === STATUS.PARSED_WITH_ERRORS) className += ' error'
 
+    console.log('initial getfill', code, currWidth)
```
Comment (awolfe76) [inline src/js/components/ValidationProgress.jsx]: A few `console.log` in here.

**Review by awolfe76 — CHANGES_REQUESTED** [review]
Just the logging.

**Comment by awolfe76** [comment]
And good catch on this one. 👀  I hadn't even noticed it.
